### ISSUE TITLE
coloring of tab characters

### ISSUE THREAD

**Issue by rgarcia** [purcell/color-theme-sanityinc-solarized#18]
Thanks for providing this! I just tried it out and immediately noticed the highlighting of tab characters:
![image](https://cloud.githubusercontent.com/assets/72655/8911421/5069fc24-3441-11e5-96ee-92430c95fb11.png)

Not sure if this is intended behavior, but it's very jarring, especially in code that makes heavy use of tabs (e.g. go code). Is there a workaround?

**Comment by purcell** [comment]
No idea why those tabs are getting highlighted. It doesn't look like `whitespace-mode`. Please can you put the cursor at the beginning of one of those lines and do `M-x describe-char`? The text properties printed out should list the faces which apply at that point -- please paste them here.

**Comment by rgarcia** [comment]
Actually on second look this appears to be a `whitespace-mode` problem. Sorry for the noise!

**Comment by purcell** [comment]
Aha. Well, the background colour I use for `whitespace-mode` is pretty much the same as in your screenshot, and I've been thinking about changing that for a while, so just let me know... :-)
