### ISSUE TITLE
this theme makes emacs very slow sometimes

### ISSUE THREAD

**Issue by banyudu** [purcell/color-theme-sanityinc-solarized#20]
In certain cases, emacs is very slow, and CPU cost very high.

### My Emacs Environment
1. OS: Windows 10 64bit
2. Emacs config repo: https://github.com/purcell/emacs.d

### Cases
1. Editing text or moving cursor in cc-mode when there are chinese comments(English comments are ok). 
2. Editing text or moving cursor in nxml-mode when there are chinese comments.
3. Editing text or moving cursor in markdown-mode when there are chinese section titles. 

### Solutions
I have tried a few times to speed up emacs. 

1. disable flyspell/flymake/flycheck:  fail
2. disable font-lock-mode: ok
3. disable-theme: ok

I am not good at elisp, so I just comment  `(require 'init-themes)` in *init.el* to speed up emacs.

**Comment by purcell** [comment]
Try `M-x customize-theme`, choose a built-in theme (e.g. tango), save the settings and then restart Emacs -- does the same problem happen after that? If so, the problem was not this theme.

**Comment by banyudu** [comment]
Thanks for your reply. Tango make emacs slow, too.  Even when `(require 'init-themes)` is commented.
So it's not this theme's bug.

**Comment by purcell** [comment]
Ah, okay.

Now, you're using my `emacs.d` config, right? So perhaps try commenting out all or parts of `init-locales.el`, e.g. the `(setq utf-translate-cjk-mode nil)` line. Let me know if that helps.

**Comment by banyudu** [comment]
Thanks, it works.
The solution is  commenting the `(set-language-environment 'utf-8)` line instead of `(setq utf-translate-cjk-mode nil)` line.

Additionally, I found *tango-dark* theme works even without commenting the line above.
