### ISSUE TITLE
Lisp error: (wrong-type-argument stringp nil)  at (file-name-directory load-file-name)

### ISSUE THREAD

**Issue by dcorking** [purcell/color-theme-sanityinc-solarized#21]
When restoring my desktop buffers with this theme, I get:

    error in process sentinel: Wrong type argument: stringp, nil

I am using version 20150803.1420 from MELPA.

This is the backtrace I get from `eval-buffer`

```lisp
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-directory(nil)
  (file-name-as-directory (file-name-directory load-file-name))
  (add-to-list (quote custom-theme-load-path) (file-name-as-directory (file-name-directory load-file-name)))
  (progn (add-to-list (quote custom-theme-load-path) (file-name-as-directory (file-name-directory load-file-name))))
  (if (boundp (quote custom-theme-load-path)) (progn (add-to-list (quote custom-theme-load-path) (file-name-as-directory (file-name-directory load-file-name)))))
  eval-buffer()  ; Reading at buffer position 39123
  #<subr call-interactively>(eval-buffer record nil)
  ad-Advice-call-interactively(#<subr call-interactively> eval-buffer record nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (eval-buffer record nil))
  call-interactively(eval-buffer record nil)
  command-execute(eval-buffer record)
  execute-extended-command(nil "eval-buffer")
  smex-read-and-run(("toggle-debug-on-error" "eval-buffer" "package-list-packages" "magit-checkout" "magit-status" "rgrep" "scratch" "shell" "compile" "whitespace-cleanup" "grep-find" "man" "revert-buffer" "make-directory" "dired" "package-list-packages-no-fetch" "magit-log" "inf-ruby" "git-blame-mode" "ibuffer" "goto-line" "whitespace-mode" "menu-bar-open" "woman" "calendar" "bury-buffer" "gfm-mode" "list-processes" "rinari-rgrep" "indent-region" "magit-diff" "recover-file" "ediff-buffers" "markdown-mode" "xterm-mouse-mode" "ruby-send-region-and-go" "ediff" "find-grep" "find-dired" "ediff-files" "magit-commit" "emacs-version" "rename-buffer" "eval-last-sexp" "find-grep-dired" "multiple-cursors-mode" "rinari-find-file-in-project" "color-theme-sanityinc-solarized-light" "snake" "magit-pull" ...))
  smex()
  #<subr call-interactively>(smex nil nil)
  ad-Advice-call-interactively(#<subr call-interactively> smex nil nil)
  apply(ad-Advice-call-interactively #<subr call-interactively> (smex nil nil))
  call-interactively(smex nil nil)
  command-execute(smex)
```

**Comment by purcell** [comment]
Please use `M-x load-file` instead of `eval-buffer` to test loading of the theme -- the backtrace you got is a red herring. If you could describe steps to reproduce this from a clean Emacs (started with `-Q`), then I can investigate. TBH, though, I doubt this is a problem related to this theme.

**Comment by dcorking** [comment]
Your theme loads cleanly with `M-x load-file`, so I am closing this issue. Thanks for guidance: I didn't realize load-file was so different from eval-buffer. I'll have to look elsewhere for my `.emacs.d` problems.

**Comment by purcell** [comment]
`load-file` binds some extra vars while it is compiling, so that the loaded file can inspect its own path, for example. Apart from that, they're not too different. The "error-in-process-sentinel" error indicates you've got something process or network related which is breaking. Perhaps setting `debug-on-error` will help you track it down.

**Comment by dcorking** [comment]
(process sentinel has some kind of guard that stops the debugger firing up. maybe there is trouble calling out to elpa or melpa.)  I wonder if we can patch the emacs lisp reference manual to mention the extra bindings in load-file, because I read it at the weekend and it implies that it is identical to eval-buffer.
