### ISSUE TITLE
ansi-color-names-vector contains background color

### ISSUE THREAD

**Issue by ryantm** [purcell/color-theme-sanityinc-solarized#23]
https://github.com/purcell/color-theme-sanityinc-solarized/blob/master/color-theme-sanityinc-solarized.el#L769 contains the background color, so that makes certain color escapes display a color that is exactly the same as the background, which makes it impossible to read without highlighting it. The color that is the background is typically the color that is white or gray.

**Comment by ryantm** [comment]
I think it should be base3 "brightwhite" instead of base03 background color.

**Comment by purcell** [comment]
Good catch, thanks. This also affected my "tomorrow" themes.
