### ISSUE TITLE
Modeline and theme colour mismatch (e.g. sanityinc-solarized-light)

### ISSUE THREAD

**Issue by dennismayr** [purcell/color-theme-sanityinc-solarized#24]
Apparently, theme `sanityinc-solarized-light` doesn't play nice with the modeline.
Not sure if it's a theme or spacemacs/emacs problem.
Any ideas?

![](https://i.imgur.com/AuYMhtQ.png)
![](https://i.imgur.com/oHOgFny.png)

**Comment by purcell** [comment]
Perhaps it's because this theme does not have definitions for the powerline evil faces? If you'd like to submit a patch based on my other theme (`color-theme-sanityinc-tomorrow`), I'd be happy to incorporate it.

**Comment by purcell** [comment]
(I'm not using this theme much myself, and it has fallen behind the `tomorrow` theme somewhat in terms of face coverage.)

**Comment by dennismayr** [comment]
I'll look into it during the following week :)

**Comment by jordanlewis** [comment]
@dennismayr @purcell did either of you figure this out? For me, `sanityinc-solarized-light` still has a very dark color for the one of the alternative colors in the modeline:

![image](https://user-images.githubusercontent.com/43821/66257981-a6f47180-e76d-11e9-9865-cc1044a3f18f.png)

Thanks for the great theme!
