### ISSUE TITLE
Mode line coloring is inverted for active buffer

### ISSUE THREAD

**Issue by Tonna** [purcell/color-theme-sanityinc-solarized#25]
Hello!

I have just loaded recent version of the theme from MELPA (color-theme-sanityinc-solarized-20190203.515). It looks like mode line colors are being inverted for active buffer (it is dark for light theme and light for dark theme). 

![screenshot_2019-02-05_01-13-10](https://user-images.githubusercontent.com/2612105/52243795-7361fe80-28e3-11e9-98e7-0eccb54a7fa8.png)

Marked text background color looks weird - it uses default dark/light background colors, but they are also inverted. 

![screenshot_2019-02-05_01-23-09](https://user-images.githubusercontent.com/2612105/52244079-a1940e00-28e4-11e9-88e0-58cd8d66ace8.png)
And cursor color is always red for some reason.

I have tried loading emacs without other packages (emacs -q) and issue persists. Using old version (color-theme-sanityinc-solarized-20160430.203) for now.

Emacs version 24.5.1
OS: Debian 9

P.S.Thank you for great color theme.

**Comment by purcell** [comment]
Thanks. Some of these were intentional (the higher-contrast region highlighting), but most were not, and have now been fixed.

I'm trying to make this theme a little more consistent with my Tomorrow themes. The two sets of themes have diverged over time. Please let me know how you get on with this new version.

**Comment by Tonna** [comment]
I have just verified fix after manual installation (most likely melpa takes time to update)  - mode line fixed. Other things look the way you explained.
Thank you!

**Comment by purcell** [comment]
Super, thanks!
